on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  lints:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v9
      - uses: DeterminateSystems/magic-nix-cache-action@v3
      - uses: cachix/cachix-action@v14
        with:
          name: snowflakeos
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          pathsToPush: |
            libsnow-generators
      - run: |
          nix build . -o libsnow-generators
